config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        password: 'admins/passwords',
      }
  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions',
        password: 'customers/passwords',
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :customers, only:[:show, :edit, :update] do
    collection do
      get ':id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
      patch ':id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    end
  end

  resources :orders, only:[:new, :create, :index, :show]  do
    collection do
      post 'comfirm'
      get 'complete'

    end
  end

  resources :addresses, except:[:show, :new]

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  #enum カラム名： {表示：integerなので整数}
  enum payment_method:  {クレジットカード:0, 銀行振込:1}

  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送待ち:3, 発送済み:4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "入金確認"
      @order.order_items.each do |order_item|
        if order_item.making_status == "製作不可"
          order_item.update(making_status: 1)
        end
      end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :created_at, :status, :shipping, :item_id)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
#ログインユーザーのみ閲覧可
  before_action :authenticate_customer!

  def new
    @order = Order.new
    @addresses = Address.all
    @address = Address.new
  end

  #注文情報の確認画面

  def comfirm

    @order = Order.new(
      customer_id: current_customer.id,
      payment_method: params[:order][:payment_method],
      shipping: 800,
      biling_amount: params[:order][:biling_amount]
    )
    if params[:order][:address_select] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name
    elsif params[:order][:address_select] == "1"
      @select = params[:order][:address_select].to_i
      @address = Address.find(@select)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    elsif params[:order][:address_select] == "2"
      @address = Address.new
      @address.postal_code = params[:order][:postal_code]
      @address.address = params[:order][:address]
      @address.name = params[:order][:name]
      @address.customer_id = current_customer.id
      if @address.save
        @order.postal_code = @address.postal_code
        @order.name = @address.name
        @order.address = @address.address
      end
    end
  end

  #注文確定
  #カート商品の注文商品への移行
  def create
    @order = Order.new(order_params)
    @order.shipping = 800
    @order.customer_id = current_customer.id
    @order.save
      @cart_items = current_customer.cart_items
      @cart_items.each do |cart_item|
        @order_item = @order.order_items.new
        @order_item.item_id = cart_item.item_id
        @order_item.item.name = cart_item.item.name
        @order_item.price = cart_item.item.add_tax_item_price
        @order_item.quantity = cart_item.amount
        @order_item.save
      end
    redirect_to complete_orders_path
    current_customer.cart_items.destroy_all
  end

  def complete
  end

  def index
    @orders = current_customer.orders


  end

  def show
    @order = Order.find(params[:id])
  end

  private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :biling_amount)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<h4 class="title">注文履歴詳細</h4>
<div class="row">
  <div class="col-6">
    <table>
      <tr>
        <th>購入者</th>
        <td>
        <%= link_to admin_customer_path(@order.customer_id) do %>
          <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %>
        </td>
      </tr>

      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>

      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.postal_code %>
          <%= @order.address %><br>
          <%= @order.name %>
        </td>
      </tr>

      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>

      <tr>
        <th>注文ステータス</th>
        <td>
        <%= form_with model: @order, url: admin_order_path, local:true do |f| %>
          <%= f.select :status, Order.statuses.keys.map{ |k| [I18n.t("enums.order.status.#{k}"),k]}, {} %>
          <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-xs-9">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% sum=0 %>
          <% @order.order_items.each do |item| %>
          <tr>
            <td><%= item.item.name %></td>
            <td><%= item.item.price %></td>
            <td><%= item.quantity %></td>
            <td><%= item.item.price*item.quantity  %></td>
              <%= form_with model: item, url: admin_order_detail_path, method: :patch, local:true do |f| %>
            <td><%= f.select :making_status, OrderItem.making_statuses.keys.map{ |k|  [I18n.t("enums.order_item.making_status.#{k}"), k]} %></td>
            <%= f.hidden_field :order_item_id, value: item.id %>
            <td><%= f.submit "更新", class: "btn btn-success" %></td>
              <% end %>
            <% sum = sum +item.item.price*item.quantity %>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-3">
    <table>
      <tr>
        <td>商品合計</td>
        <td><%= sum %>円</td>
      </tr>
      <tr>
        <td>送料</td>
        <td><%= @order.shipping %>円</td>
      </tr>
        <% @order.biling_amount = sum+@order.shipping %>
      <tr>
        <td><strong>請求金額合計</strong></td>
        <td><strong><%= @order.biling_amount %>円</strong></td>
      </tr>
    </table>
  </div>
</div>