config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        password: 'admins/passwords',
      }
  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions',
        password: 'customers/passwords',
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :customers, only:[:show, :edit, :update] do
    collection do
      get ':id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
      patch ':id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    end
  end

  resources :orders, only:[:new, :create, :index, :show]  do
    collection do
      post 'comfirm'
      get 'complete'

    end
  end

  resources :addresses, except:[:show, :new]

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private
  def customer_params
    params.require(:customer).permit(:id, :create_name, :create_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     customer_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  #退会後のログインを阻止
   before_action :reject_inactive_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_active
        redirect_to new_customer_session_path
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   #ログインユーザーのみ閲覧可能
  before_action :authenticate_customer!, only: [:edit, :withdrawal]

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
  end

  def withdrawal
    @customer = Customer.find(params[:id])
    @customer.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="title">
  <h4>会員情報編集</h4>
</div>

<%= form_with model: @customer, local:true do |f| %>
<table>
  <tr>
    <td>氏名</td>
    <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
  </tr>
  <tr>
    <td>フリガナ</td>
    <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td><%= f.text_field :postal_code %></td>
  </tr>
  <tr>
    <td>住所</td>
    <td><%= f.text_field :address, style: "width: 80%;" %></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td><%= f.text_field :telephone_number %></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.submit "編集内容を保存", class: "btn btn-success" %></td>
    <td><%= link_to "退会する", unsubscribe_customers_path, class: "btn btn-danger" %></td>
  </tr>
</table>
<% end %>

app/views/customers/show.html.erb
<div class="title">
  <h4>マイページ</h4>
</div>

<div class="form">
  <strong>登録情報</strong>
  <%= link_to "編集する", edit_customer_path(@customer.id), class: "btn btn-success" %>
</div>

<div class="row">
  <div class="col-xs-8">
    <table class="table table-bordered">
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>カナ</td>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
    </table>
  </div>
</div>

<div class="form">
  <strong>配送先</strong>
  <%= link_to "一覧を見る", addresses_path, class: "btn btn-primary" %>
</div>

<div class="form">
  <strong>注文履歴</strong>
  <%= link_to "一覧を見る", orders_path, class: "btn btn-primary" %>
</div>

app/views/customers/unsubscribe.html.erb
<div class="unsubsucribe">
  <h5><strong>本当に退会しますか？</strong></h5>
</div>

<div class="unsubsucribe">
  <p>退会すると、会員登録情報や<br>
  これまでの購入履歴が閲覧できなくなります。<br>
  退会する場合は、「退会する」をクリックしてください。</p>
</div>

<div>
  <%= link_to "退会しない", customer_path(current_customer.id), class: "btn btn-primary" %>
  <%= link_to "退会する", withdrawal_customers_path(@customer), method: :patch, class: "btn btn-danger" %>
</div>