config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        password: 'admins/passwords',
      }
  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions',
        password: 'customers/passwords',
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :customers, only:[:show, :edit, :update] do
    collection do
      get ':id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
      patch ':id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    end
  end

  resources :orders, only:[:new, :create, :index, :show]  do
    collection do
      post 'comfirm'
      get 'complete'

    end
  end

  resources :addresses, except:[:show, :new]

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item



end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  #ログインユーザーのみ閲覧可能
  before_action :authenticate_customer!

  def index
    @cart_items =  current_customer.cart_items
  end

  def create
    #ログインユーザーのカートアイテムを作成する記述
    @cart_item = current_customer.cart_items.new(item_params)
    @cart_item.save
    redirect_to cart_items_path
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
  end

  private
  def item_params
    params.require(:cart_item).permit(:customer_id, :item_id, :amount)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="cation">
  <h4>ショッピングカート</h4>
</div>

<div align="right">
  <%= link_to "カートを空にする", destroy_all_cart_items_path, method: :delete, class: "btn btn-danger" %>
</div>

<table border="1", width="100%">
  <thead class="thead-light">
    <tr>
      <td>商品名</td>
      <td>単価(税込)</td>
      <td>数量</td>
      <td>小計</td>
      <td></td>
    </tr>
  </thead>
  <% sum=0 %>
  <% @cart_items.each do |cart_item| %>
  <tr>
    <td>
      <%= attachment_image_tag cart_item.item, :image, :fill, 60, 40, format:'jpeg' %>
      <%= cart_item.item.name %>
    </td>
    <td><%= cart_item.item.add_tax_item_price %></td>
    <td>
      <%= form_with model: cart_item, local:true do |f| %>
        <%= f.select :amount, [1,2,3,4,5,6,7,8,9,10] %>
        <%= f.submit "変更", class: "btn btn-success" %>
      <% end %>
    </td>
    <td>
      <%= cart_item.item.add_tax_item_price*cart_item.amount %>
    </td>
    <td><%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn btn-danger" %></td>
  </tr>
  <% sum = sum+cart_item.item.add_tax_item_price*cart_item.amount %>
  <% end %>
</table>

<div class="row">
  <div class="col-4">
    <%= link_to "買い物を続ける", root_path, class: "btn btn-primary" %>
  </div>
  <div class="col-4 offset-4">
    <table border="1">
      <tr>
        <td>合計金額</td>
        <td><%= sum %></td>
      </tr>
    </table>
  </div>
</div>

<div>
  <%= link_to "情報入力に進む", new_order_path, class: "btn btn-success" %>
</div>