config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        password: 'admins/passwords',
      }
  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions',
        password: 'customers/passwords',
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :customers, only:[:show, :edit, :update] do
    collection do
      get ':id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
      patch ':id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    end
  end

  resources :orders, only:[:new, :create, :index, :show]  do
    collection do
      post 'comfirm'
      get 'complete'

    end
  end

  resources :addresses, except:[:show, :new]

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_info
    self.postal_code + self.address + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  attachment :image

  def  add_tax_item_price #税込価格
    (self.price * 1.10).round
  end



end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  #enum カラム名： {表示：integerなので整数}
  enum payment_method:  {クレジットカード:0, 銀行振込:1}

  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送待ち:3, 発送済み:4}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: {製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  before_action :authenticate_customer!

  def index
    @customer = current_customer
    @address = Address.new
    @addresses = Address.all
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path
    else
      @addresses = Address.all
      render :index
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:name, :postal_code, :address, :customer_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.limit(4)
  end

  def about
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    @quantity = Item.count
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
#ログインユーザーのみ閲覧可
  before_action :authenticate_customer!

  def new
    @order = Order.new
    @addresses = Address.all
    @address = Address.new
  end

  #注文情報の確認画面

  def comfirm

    @order = Order.new(
      customer_id: current_customer.id,
      payment_method: params[:order][:payment_method],
      shipping: 800,
      biling_amount: params[:order][:biling_amount]
    )
    if params[:order][:address_select] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name
    elsif params[:order][:address_select] == "1"
      @select = params[:order][:address_select].to_i
      @address = Address.find(@select)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    elsif params[:order][:address_select] == "2"
      @address = Address.new
      @address.postal_code = params[:order][:postal_code]
      @address.address = params[:order][:address]
      @address.name = params[:order][:name]
      @address.customer_id = current_customer.id
      if @address.save
        @order.postal_code = @address.postal_code
        @order.name = @address.name
        @order.address = @address.address
      end
    end
  end

  #注文確定
  #カート商品の注文商品への移行
  def create
    @order = Order.new(order_params)
    @order.shipping = 800
    @order.customer_id = current_customer.id
    @order.save
      @cart_items = current_customer.cart_items
      @cart_items.each do |cart_item|
        @order_item = @order.order_items.new
        @order_item.item_id = cart_item.item_id
        @order_item.item.name = cart_item.item.name
        @order_item.price = cart_item.item.add_tax_item_price
        @order_item.quantity = cart_item.amount
        @order_item.save
      end
    redirect_to complete_orders_path
    current_customer.cart_items.destroy_all
  end

  def complete
  end

  def index
    @orders = current_customer.orders


  end

  def show
    @order = Order.find(params[:id])
  end

  private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :biling_amount)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <p class="welcome">ようこそ、<%= current_customer.last_name %>さん！</p>
            <li class="nav-item">
              <%= link_to 'マイページ', customer_path(current_customer.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧",  admin_genres_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="pt-5">
      <div class= "container">

          <%= yield %>
      </div>
    </main>
    <footer class="bg-white text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>